### ISSUE TITLE
markbot issue 

### ISSUE THREAD

**Issue by Elisa0122** [Elisa0122/euro-just-doing-semantics#1]
@KarenMendozaGarza

Could you help me to understand why markbot don't pass please?

<img width="780" alt="Screen Shot 2022-01-14 at 10 29 33 AM" src="https://user-images.githubusercontent.com/83783101/149541056-e4020fdb-6ea1-4de0-aeb3-cb31c02afcbf.png">

Thank you

**Comment by KarenMendozaGarza** [comment]
It's just a spelling error. Change it from dat**a**time to dat**e**time, and you should be good to go:)
